name: CI Update
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 3"
  
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
       token: ${{ secrets.RENOVATE_TOKEN }}
       repository: juliakroger/go-corona
          
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: john@example.com
        AUTHOR_NAME: john
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
