name: Renovate
on:
  workflow_dispatch:
  
#   schedule:
#     - cron: '0/30 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          repository: juliakroger/go-corona
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          
      - name: Run CI
        run: npm ci
        
      - name: Upgrade packages 🔀
        run: npm update
        
      - name: Commit and create PR 🔀
        uses: peter-evans/create-pull-request@v3
        with:
          title: "build(deps): Upgrade NPM packages (automated)"
          branch: "build-deps-upgrade-npm-packages-automated"
          commit-message: "build(deps): upgrade NPM packages (automated)"
#           token: ${{ secrets.RENOVATE_TOKEN }}
          
#       - name: Self-hosted Renovate
#         uses: renovatebot/github-action@v32.0.1
#         with:
#           configurationFile: example/renovate-config.js
#           token: ${{ secrets.RENOVATE_TOKEN }}
#         env:
#           LOG_LEVEL: 'debug'
          
          
#       - name: Get token
#         id: get_token
#         uses: machine-learning-apps/actions-app-token@master
#         with:
#           APP_PEM: ${{ secrets.APP_PEM }}
#           APP_ID: ${{ secrets.APP_ID }}


#       - name: Self-hosted Renovate
#         uses: renovatebot/github-action@v32.0.1
#         with:
#           configurationFile: example/renovate-config.js
#           token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'
